development:
  adapter: postgresql
  encoding: utf8
  database: legacy-blog-app_development
  pool: 5
  username: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: legacy-blog-app_test
  pool: 5
  username: postgres
  min_messages: WARNING
  host: localhost
  template: template0
